# Terminal colors
set -ga terminal-overrides ",xterm-256color*:Tc"
set-option -g default-terminal "screen-256color"

# Use Ctrl-a instead of Ctrl-b
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Open new window in current path
bind c new-window -c "#{pane_current_path}"

# Faster escape from Vim
set -sg escape-time 0

# Start window and pane numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Mouse support
set -g mouse on

# Toggle mousee
bind a if-shell '[ "$(tmux show -gv mouse)" = "on" ]' \
    'set -g mouse off' \
    'set -g mouse on'

# Theme
set -g status-style "bg=default"
set -g status-left-length 30
set -g status-left "#[bg=#dcdfe4,fg=#000000] #S #[default] "
set -g status-right-length 30
set -g status-right " \
#[bg=#e06c75,fg=#000000]#{?mouse,, !M }#[default]#{?mouse,, }\
#[bg=#e5c07b,fg=#000000]#{?client_prefix, C ,}#[default]#{?client_prefix, ,}\
#[bg=#dcdfe4,fg=#000000] #{b:pane_current_path} #[default]\
"
set -g status-justify left
setw -g window-status-format "#[bg=#282c34,fg=#dcdfe4] #I:#W "
setw -g window-status-current-format "#[bg=#98c379,fg=#000000] #I:#W #[default]"
set -g pane-border-style "fg=default"
set -g pane-active-border-style "fg=#61afef"
set -g message-style "bg=#89b4fa,fg=#000000"
